[package]
name = "day04"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.22"
num = "0.4.3"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
